# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Java CI with Maven

on:
  push:
    branches:
      - v0.6-cache

env:
  ES_JAVA_OPTS: "-Xms256m -Xmx512m"
  BUILD_MAVEN_OPTS: "-DskipTests=true --batch-mode --also-make"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Get branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: get_branch

      - name: Build with Maven
      - run: |
          branch_name=${{ steps.get_branch.outputs.branch }}
          if [[ $branch_name == ' v0.6-cache' ]]
          then
              echo "Building branch ${branch_name}"
              mvn clean install -Dcheckstyle.skip -Drat.skip=true -Dit.skip=true -Denforcer.skip=true -Dmaven.javadoc.skip=true ${{ env.BUILD_MAVEN_OPTS }}


      - name: Publish to GitHub Packages Apache Maven
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.my_pat }}
